---
title: "About"
---

## Professional

I currently work as a data scientist at Capital One Canada.
Working on the customer acquisitions team, I build and maintain core risk and valuations models that help us make approve/decline decisions and the amount of credit to extend to prospective customers.

Before I started my current job, I studied at the University of Waterloo (UW), where I graduated in 2019 with a bachelor of mathematics, honours in statistics and a minor in economic theory.

## Personal

I'm originally from Montreal. Because of the co-op program at UW, I've had the chance to live in a few cities during my studies:

- Waterloo, while studying and working as a NSERC research assistant
- Ottawa, while working as a research intern at Statistics Canada
- Toronto, while working as a data scientist co-op at Capital One

I appreciated getting the chance to live in each of these cities for an extended period of time, and I think it allowed me to get to know each place in a way that just visiting would not have.

In my spare time, I enjoy cycling, both for transportation and fitness, baking artisan-style bread, and rock climbing. I am actively involved in housing advocacy at [More Neighbours Toronto](https://www.moreneighbours.ca/), where we work to break down the barriers that prevent badly needed new housing from being built. A few times a year, I'll go on a reading binge, devouring multiple books in the span of a weekend. Sometimes, when I don't feel like it's just working more, I'll do a little data-related side project that is a bit different from my work, just so I don't feel like I'm working on my own spare time.


