name: Schedule merge

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: '43 10 * * *'

permissions:
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  statuses: write
      
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: squash
          # Time zone to use. Default is UTC.
          time_zone: 'America/Edmonton'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
